# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a51d73a6b98edf90db0dcf607ea1b3f44d0bd28c47b94c565ef76089fd04bca834122af3a1070d53e51accc3966991e0126cae01188932052fa09ce8dc529e7

test:
  secret_key_base: e233219defa624bd7894801ac22ea1b5c7f8a2bc8902132f7693c5a15f0849a0f60117f335ae8ff8b150f0d4d26bde297e9a32f2ec059f571f885dc25f443863

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
